# this is our development docker-compose building on top of the production docker-compose, just mounting
# the sync image - not redefining anything else

version: "2"
services:
  app-unison:
    volumes:
      - appcode-unison-sync:/var/www:nocopy # will be mounted on /var/www

# that the important thing
volumes:
  appcode-unison-sync:
    external: true
